// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $alphabet from "./routes/alphabet.tsx";
import * as $custom from "./routes/custom.tsx";
import * as $index from "./routes/index.tsx";
import * as $numpad from "./routes/numpad.tsx";
import * as $quotes from "./routes/quotes.tsx";
import * as $HamburgerMenu from "./islands/HamburgerMenu.tsx";
import * as $KeyLogger from "./islands/KeyLogger.tsx";
import * as $RenderedQuoteResult from "./islands/RenderedQuoteResult.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/alphabet.tsx": $alphabet,
    "./routes/custom.tsx": $custom,
    "./routes/index.tsx": $index,
    "./routes/numpad.tsx": $numpad,
    "./routes/quotes.tsx": $quotes,
  },
  islands: {
    "./islands/HamburgerMenu.tsx": $HamburgerMenu,
    "./islands/KeyLogger.tsx": $KeyLogger,
    "./islands/RenderedQuoteResult.tsx": $RenderedQuoteResult,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
