// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $alphabet from "./routes/alphabet.tsx";
import * as $api_admin_refresh_cache from "./routes/api/admin/refresh-cache.ts";
import * as $api_code_collections_categories_lang_ from "./routes/api/code-collections/categories/[lang].ts";
import * as $api_code_collections_collections_lang_ from "./routes/api/code-collections/collections/[lang].ts";
import * as $api_code_collections_content_lang_category_id_ from "./routes/api/code-collections/content/[lang]/[category]/[id].ts";
import * as $api_code_collections_languages from "./routes/api/code-collections/languages.ts";
import * as $api_code_collections_metadata_lang_category_ from "./routes/api/code-collections/metadata/[lang]/[category].ts";
import * as $api_code_collections_random_snippet_lang_ from "./routes/api/code-collections/random-snippet/[lang].ts";
import * as $api_code_collections_snippets_lang_id_ from "./routes/api/code-collections/snippets/[lang]/[id].ts";
import * as $api_game_stats from "./routes/api/game-stats.ts";
import * as $api_github_content from "./routes/api/github-content.ts";
import * as $api_quotes_categories_lang_ from "./routes/api/quotes/categories/[lang].ts";
import * as $api_quotes_content_lang_category_id_ from "./routes/api/quotes/content/[lang]/[category]/[id].ts";
import * as $api_quotes_languages from "./routes/api/quotes/languages.ts";
import * as $api_quotes_metadata_lang_category_ from "./routes/api/quotes/metadata/[lang]/[category].ts";
import * as $api_translations_lang_ from "./routes/api/translations/[lang].ts";
import * as $api_translations_all from "./routes/api/translations/all.ts";
import * as $api_translations_languages from "./routes/api/translations/languages.ts";
import * as $api_trigraphs from "./routes/api/trigraphs.ts";
import * as $api_trigraphs_name_ from "./routes/api/trigraphs/[name].ts";
import * as $code from "./routes/code.tsx";
import * as $custom from "./routes/custom.tsx";
import * as $index from "./routes/index.tsx";
import * as $quotes from "./routes/quotes.tsx";
import * as $random from "./routes/random.tsx";
import * as $serverstats from "./routes/serverstats.tsx";
import * as $trigraphs from "./routes/trigraphs.tsx";
import * as $userstats from "./routes/userstats.tsx";
import * as $CodeTyperMode from "./islands/CodeTyperMode.tsx";
import * as $GameScoreDisplayIsland from "./islands/GameScoreDisplayIsland.tsx";
import * as $GlobalLanguageSelector from "./islands/GlobalLanguageSelector.tsx";
import * as $HamburgerMenu from "./islands/HamburgerMenu.tsx";
import * as $KeyLogger from "./islands/KeyLogger.tsx";
import * as $KeyboardHeatmapIsland from "./islands/KeyboardHeatmapIsland.tsx";
import * as $QuoteTyperMode from "./islands/QuoteTyperMode.tsx";
import * as $RandomSettings from "./islands/RandomSettings.tsx";
import * as $ReactiveDescription from "./islands/ReactiveDescription.tsx";
import * as $RenderedQuoteResult from "./islands/RenderedQuoteResult.tsx";
import * as $StatsPage from "./islands/StatsPage.tsx";
import * as $TranslationInitializer from "./islands/TranslationInitializer.tsx";
import * as $TrigraphsTyperMode from "./islands/TrigraphsTyperMode.tsx";
import * as $UserStatsIsland from "./islands/UserStatsIsland.tsx";
import * as $UserStatsPageContentIsland from "./islands/UserStatsPageContentIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/alphabet.tsx": $alphabet,
    "./routes/api/admin/refresh-cache.ts": $api_admin_refresh_cache,
    "./routes/api/code-collections/categories/[lang].ts":
      $api_code_collections_categories_lang_,
    "./routes/api/code-collections/collections/[lang].ts":
      $api_code_collections_collections_lang_,
    "./routes/api/code-collections/content/[lang]/[category]/[id].ts":
      $api_code_collections_content_lang_category_id_,
    "./routes/api/code-collections/languages.ts":
      $api_code_collections_languages,
    "./routes/api/code-collections/metadata/[lang]/[category].ts":
      $api_code_collections_metadata_lang_category_,
    "./routes/api/code-collections/random-snippet/[lang].ts":
      $api_code_collections_random_snippet_lang_,
    "./routes/api/code-collections/snippets/[lang]/[id].ts":
      $api_code_collections_snippets_lang_id_,
    "./routes/api/game-stats.ts": $api_game_stats,
    "./routes/api/github-content.ts": $api_github_content,
    "./routes/api/quotes/categories/[lang].ts": $api_quotes_categories_lang_,
    "./routes/api/quotes/content/[lang]/[category]/[id].ts":
      $api_quotes_content_lang_category_id_,
    "./routes/api/quotes/languages.ts": $api_quotes_languages,
    "./routes/api/quotes/metadata/[lang]/[category].ts":
      $api_quotes_metadata_lang_category_,
    "./routes/api/translations/[lang].ts": $api_translations_lang_,
    "./routes/api/translations/all.ts": $api_translations_all,
    "./routes/api/translations/languages.ts": $api_translations_languages,
    "./routes/api/trigraphs.ts": $api_trigraphs,
    "./routes/api/trigraphs/[name].ts": $api_trigraphs_name_,
    "./routes/code.tsx": $code,
    "./routes/custom.tsx": $custom,
    "./routes/index.tsx": $index,
    "./routes/quotes.tsx": $quotes,
    "./routes/random.tsx": $random,
    "./routes/serverstats.tsx": $serverstats,
    "./routes/trigraphs.tsx": $trigraphs,
    "./routes/userstats.tsx": $userstats,
  },
  islands: {
    "./islands/CodeTyperMode.tsx": $CodeTyperMode,
    "./islands/GameScoreDisplayIsland.tsx": $GameScoreDisplayIsland,
    "./islands/GlobalLanguageSelector.tsx": $GlobalLanguageSelector,
    "./islands/HamburgerMenu.tsx": $HamburgerMenu,
    "./islands/KeyLogger.tsx": $KeyLogger,
    "./islands/KeyboardHeatmapIsland.tsx": $KeyboardHeatmapIsland,
    "./islands/QuoteTyperMode.tsx": $QuoteTyperMode,
    "./islands/RandomSettings.tsx": $RandomSettings,
    "./islands/ReactiveDescription.tsx": $ReactiveDescription,
    "./islands/RenderedQuoteResult.tsx": $RenderedQuoteResult,
    "./islands/StatsPage.tsx": $StatsPage,
    "./islands/TranslationInitializer.tsx": $TranslationInitializer,
    "./islands/TrigraphsTyperMode.tsx": $TrigraphsTyperMode,
    "./islands/UserStatsIsland.tsx": $UserStatsIsland,
    "./islands/UserStatsPageContentIsland.tsx": $UserStatsPageContentIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
