name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
      security-events: write # Needed for CodeQL to write findings

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: "javascript-typescript"
          # queries: +security-extended # Optional: Uncomment to include more security queries

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Check code formatting
        run: deno fmt --check --ignore="components/QuoteTextDisplay.tsx" --ignore="memory-bank/*" --ignore="static/*"

      - name: Lint code
        run: deno lint

      - name: Check for type and module errors
        run: deno check main.ts # Specify relevant entry points/files

      - name: Run tests
        run: deno task test

      - name: Build step
        run: "deno task build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "typetutor"
          entrypoint: "main.ts"
          root: "."
        env:
          USE_DENO_KV: "true"
          # DENO_KV_PATH: "./data/kv.db" # Optional: configure KV path if needed for your Deno Deploy setup. Deno Deploy provides a managed KV store.
